# Generated by Django 5.2.9 on 2025-12-19 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=15)),
                ('hoten', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('khoa', models.CharField(choices=[('cntt', 'Công nghệ thông tin'), ('ck', 'Cơ khí'), ('dt', 'Điện tử')])),
                ('maths', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('physics', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('chemistry', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
            ],
        ),
    ]
